version: '3'
services:
    dlimiter:
        image: steve0x2a/dlimiter
        restart: always
        volumes:
            - ./conf:/app/conf
        ports:
            - 8088:8088
        environment: 
            - DLIMITER_CN_UPDATE=true
            - DLIMITER_AUTO_UPDATE=true
            - DLIMITER_PORT=8088
            - TZ=Asia/Shanghai
            #- DLIMITER_REPO_URL="https://ghproxy.com/https://github.com/Steve0x2a/DLimiter.git" # 当你访问github网络很差时，可以考虑解除本行注释
        hostname: dlimiter
        container_name: dlimiter