version: '3'
services:
    dlimiter:
        image: steve0x2a/dlimiter
        restart: always
        volumes:
            - ./conf:/app/conf
        ports:
            - 8088:8088
        environment: 
            - DLIMITER_CN_UPDATE=true
            - DLIMITER_AUTO_UPDATE=true
            - TZ=Asia/Shanghai
        hostname: dlimiter
        container_name: dlimiter