name: Build DLimiter Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - main.py
      - docker/Dockerfile
      - docker/start.sh
      - .github/workflows/build.yml
      - requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dlimiter:latest

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/dlimiter
          short-description: 用于下载器平衡PT上传和外网视频播放的限速器
          readme-filepath: ./README.md